### ISSUE TITLE
Error when executing main.py

### ISSUE THREAD

**Issue by agoodweathercc** [JiaxuanYou/graph-generation#3]
Hello, 

When I execute main.py. I had the following error.

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from train import *
  File "/home/Documents/DeepLearning/graph-generation/train.py", line 24, in <module>
    from utils import *
  File "/home/Documents/DeepLearning/graph-generation/utils.py", line 17, in <module>
    import data
  File "/home/Documents/DeepLearning/graph-generation/data.py", line 17, in <module>
    from model import *
  File "/home/Documents/DeepLearning/graph-generation/model.py", line 989
    prob = x_prev @ x_last.permute(0,2,1)
                  ^
SyntaxError: invalid syntax

**Comment by Takonan** [comment]
Are you using Python 3? The `@` operator performs matmul: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul
